#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist). You can
  # override these by including one of the net-*.yaml environment files,
  # such as net-bond-with-vlans.yaml, or modifying the list here.
  # Port assignments for the Controller
  OS::TripleO::Controller::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/controller.yaml
  # Port assignments for the Compute
  OS::TripleO::Compute::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/compute.yaml
  # Port assignments for the BlockStorage
  OS::TripleO::BlockStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/cinder-storage.yaml
  # Port assignments for the ObjectStorage
  OS::TripleO::ObjectStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/swift-storage.yaml
  # Port assignments for the CephStorage
  OS::TripleO::CephStorage::Net::SoftwareConfig:
    ../network/config/single-nic-vlans/ceph-storage.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  #
  # NOTE: (Since Rocky)
  # ControlPlaneSubnetCidr: It is no longer a requirement to provide the
  #                         parameter. The attribute is resolved from the
  #                         ctlplane subnet(s).
  # ControlPlaneDefaultRoute: It is no longer a requirement to provide this
  #                           parameter. The attribute is resolved from the
  #                           ctlplane subnet(s).
  # EC2MetadataIp: It is no longer a requirement to provide this parameter. The
  #                attribute is resolved from the ctlplane subnet(s).
  #

  # Customize the IP subnet to match the local environment
  StorageNetCidr: '172.16.1.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageAllocationPools: [{'start': '172.16.1.128', 'end': '172.16.1.250'}]
  # Customize the VLAN ID to match the local environment
  StorageNetworkVlanID: 30

  # Customize the IP subnet to match the local environment
  StorageMgmtNetCidr: '172.16.3.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageMgmtAllocationPools: [{'start': '172.16.3.128', 'end': '172.16.3.250'}]
  # Customize the VLAN ID to match the local environment
  StorageMgmtNetworkVlanID: 40

  # Customize the IP subnet to match the local environment
  InternalApiNetCidr: '172.16.2.0/24'
  # Customize the IP range to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '172.16.2.128', 'end': '172.16.2.250'}]
  # Customize the VLAN ID to match the local environment
  InternalApiNetworkVlanID: 20

  # Customize the IP subnet to match the local environment
  TenantNetCidr: '172.16.0.0/24'
  # Customize the IP range to use for static IPs and VIPs
  TenantAllocationPools: [{'start': '172.16.0.128', 'end': '172.16.0.250'}]
  # Customize the VLAN ID to match the local environment
  TenantNetworkVlanID: 50

  # Customize the IP subnet to match the local environment
  ExternalNetCidr: '192.168.3.0/24'
  # Customize the IP range to use for static IPs and VIPs
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '192.168.3.200', 'end': '192.168.3.220'}]
  # Gateway router for routable networks
  ExternalInterfaceDefaultRoute: '192.168.3.1'
  # Customize the VLAN ID to match the local environment
  ExternalNetworkVlanID: 10

  # Customize the IP subnet to match the local environment
  ManagementNetCidr: '10.0.1.0/24'
  # Customize the IP range to use for static IPs and VIPs
  ManagementAllocationPools: [{'start': '10.0.1.128', 'end': '10.0.1.250'}]
  # Customize the VLAN ID to match the local environment
  ManagementNetworkVlanID: 60

  # Define the DNS servers (maximum 2) for the overcloud nodes
  # When the list is no set or empty, the nameservers on the ctlplane subnets will be used.
  # (ctlplane subnets nameservers are controlled by the ``undercloud_nameservers`` option in ``undercloud.conf``)
  DnsServers: []
  # List of Neutron network types for tenant networks (will be used in order)
  NeutronNetworkType: 'vxlan,vlan'
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 'datacentre:1:1000'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=active-backup"

  # ControlFixedIPs: [{'ip_address':'.201.101'}]
  InternalApiVirtualFixedIPs: [{'ip_address':'172.16.2.9'}]
  PublicVirtualFixedIPs: [{'ip_address':'192.168.3.196'}]
  StorageVirtualFixedIPs: [{'ip_address':'172.16.1.9'}]
  StorageMgmtVirtualFixedIPs: [{'ip_address':'172.16.3.9'}]
  RedisVirtualFixedIPs: [{'ip_address':'172.16.2.8'}]
