resource_registry:
  # This section is usually not modified, if in doubt stick to the defaults
  # TripleO overcloud networks
  OS::TripleO::Network::External: /home/stack/overcloud-validation/network/external.yaml
  OS::TripleO::Network::InternalApi: /home/stack/overcloud-validation/network/internal_api.yaml
  # OS::TripleO::Network::StorageMgmt: OS::Heat::None
  OS::TripleO::Network::StorageMgmt: /home/stack/overcloud-validation/network/storage_mgmt.yaml
  OS::TripleO::Network::Storage: /home/stack/overcloud-validation/network/storage.yaml
  OS::TripleO::Network::Tenant: /home/stack/overcloud-validation/network/tenant.yaml

  # Port assignments for the VIPs
  OS::TripleO::Network::Ports::ExternalVipPort: /home/stack/overcloud-validation/network/ports/external.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: /home/stack/overcloud-validation/network/ports/internal_api.yaml
  OS::TripleO::Network::Ports::StorageVipPort: /home/stack/overcloud-validation/network/ports/storage.yaml
  #OS::TripleO::Network::Ports::StorageMgmtVipPort: OS::Heat::None
  OS::TripleO::Network::Ports::StorageMgmtVipPort: /home/stack/overcloud-validation/network/ports/storage_mgmt.yaml
  OS::TripleO::Network::Ports::TenantVipPort: /home/stack/overcloud-validation/network/ports/tenant.yaml
  OS::TripleO::Network::Ports::RedisVipPort: /home/stack/overcloud-validation/network/ports/vip.yaml

  # Port assignments for the controller role
  OS::TripleO::Controller::Ports::ExternalPort: /home/stack/overcloud-validation/network/ports/external.yaml
  OS::TripleO::Controller::Ports::InternalApiPort: /home/stack/overcloud-validation/network/ports/internal_api.yaml
  OS::TripleO::Controller::Ports::StoragePort: /home/stack/overcloud-validation/network/ports/storage.yaml
  #OS::TripleO::Controller::Ports::StorageMgmtPort: OS::Heat::None
  OS::TripleO::Controller::Ports::StorageMgmtPort: /home/stack/overcloud-validation/network/ports/storage_mgmt.yaml
  OS::TripleO::Controller::Ports::TenantPort: /home/stack/overcloud-validation/network/ports/tenant.yaml

  # Port assignments for the controller role
  OS::TripleO::Standalone::Ports::ExternalPort: /home/stack/overcloud-validation/network/ports/external.yaml
  OS::TripleO::Standalone::Ports::InternalApiPort: /home/stack/overcloud-validation/network/ports/internal_api.yaml
  OS::TripleO::Standalone::Ports::StoragePort: /home/stack/overcloud-validation/network/ports/storage.yaml
  OS::TripleO::Standalone::Ports::StorageMgmtPort: /home/stack/overcloud-validation/network/ports/storage_mgmt.yaml
  OS::TripleO::Standalone::Ports::TenantPort: /home/stack/overcloud-validation/network/ports/tenant.yaml

  # Port assignments for the compute role
  OS::TripleO::Compute::Ports::InternalApiPort: /home/stack/overcloud-validation/network/ports/internal_api.yaml
  OS::TripleO::Compute::Ports::StoragePort: /home/stack/overcloud-validation/network/ports/storage.yaml
  OS::TripleO::Compute::Ports::TenantPort: /home/stack/overcloud-validation/network/ports/tenant.yaml

parameter_defaults:
  ServiceNetMap:
    ApacheNetwork: internal_api
    NeutronTenantNetwork: tenant
    CeilometerApiNetwork: internal_api
    ContrailAnalyticsNetwork: internal_api
    ContrailAnalyticsDatabaseNetwork: internal_api
    ContrailConfigNetwork: internal_api
    ContrailControlNetwork: internal_api
    ContrailDatabaseNetwork: internal_api
    ContrailWebuiNetwork: internal_api
    ContrailTsnNetwork: internal_api
    AodhApiNetwork: internal_api
    PankoApiNetwork: internal_api
    BarbicanApiNetwork: internal_api
    GnocchiApiNetwork: internal_api
    MongodbNetwork: internal_api
    CinderApiNetwork: internal_api
    CinderIscsiNetwork: storage
    CongressApiNetwork: internal_api
    GlanceApiNetwork: internal_api
    IronicApiNetwork: ctlplane
    IronicNetwork: ctlplane
    IronicInspectorNetwork: ctlplane
    KeystoneAdminApiNetwork: ctlplane # allows undercloud to config endpoints
    KeystonePublicApiNetwork: internal_api
    ManilaApiNetwork: internal_api
    NeutronApiNetwork: internal_api
    OctaviaApiNetwork: internal_api
    HeatApiNetwork: internal_api
    HeatApiCfnNetwork: internal_api
    HeatApiCloudwatchNetwork: internal_api
    NovaApiNetwork: internal_api
    NovaColdMigrationNetwork: ctlplane
    NovaPlacementNetwork: internal_api
    NovaMetadataNetwork: internal_api
    NovaVncProxyNetwork: internal_api
    NovaLibvirtNetwork: internal_api
    Ec2ApiNetwork: internal_api
    Ec2ApiMetadataNetwork: internal_api
    TackerApiNetwork: internal_api
    SwiftStorageNetwork: storage # Changed from storage_mgmt
    SwiftProxyNetwork: storage
    SaharaApiNetwork: internal_api
    HorizonNetwork: internal_api
    MemcachedNetwork: internal_api
    RabbitmqNetwork: internal_api
    QdrNetwork: internal_api
    RedisNetwork: internal_api
    MysqlNetwork: internal_api
    CephClusterNetwork: storage # Changed from storage_mgmt
    CephMonNetwork: storage
    CephRgwNetwork: storage
    PublicNetwork: external
    OpendaylightApiNetwork: internal_api
    OvnDbsNetwork: internal_api
    MistralApiNetwork: internal_api
    ZaqarApiNetwork: internal_api
    PacemakerRemoteNetwork: internal_api
    EtcdNetwork: internal_api
    CephStorageHostnameResolveNetwork: storage
    ControllerHostnameResolveNetwork: internal_api
    ComputeHostnameResolveNetwork: internal_api
    ObjectStorageHostnameResolveNetwork: internal_api
    BlockStorageHostnameResolveNetwork: internal_api

